### PR TITLE
Stop code mtc fix

### LINKED ISSUE #317: MTC feed merge fails if stop_code missing from first record
A `TODO` was never handled properly in the feed merging logic.

https://github.com/ibi-group/datatools-server/blob/77843cbe2b869e8dc066bac4868bef3768e9b3f0/src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java#L487-L491

Instead of this approach, discussion with MTC has yielded a new approach:
1. We identify location_types 1, 2, 3, and 4 (anything but 0 or blank) and ignore them in stop_code check.
   1. These location_types will always be merged on stop_id
1. For location_type 0 or blank, we check for stop_code in both feeds that are being merged.  
   1. If the future feed doesn't have all stop_code values, merging should stop with an error message that clearly describe the issue.
   1. If future feed doesn't have any stop_code value, merging should be on stop_id with a warning message abou tthe missing stop_code for that location_type.

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fix #317 with new stop_code handling logic:

Before reading any lines in stops.txt, first determine whether all records contain
properly filled stop_codes. The rules governing this logic are as follows (see item 4 in [updated docs](https://github.com/ibi-group/datatools-ui/blob/206e3380460350df4edb347e51e31c6636fbf8b3/docs/user/merging-feeds.md#merge-rules)):
1. Stops will be merged on stop_code or stop_id if stop_code is missing. However, some restrictions apply on when missing stop_code values are permitted:
    1. Stops with location_type greater than 0 (i.e., anything but 0 or empty) are permitted to have empty stop_codes (even if there are other stops in the feed that have stop_code values). This is because these location_types represent special entries that are either stations, entrances/exits, or generic nodes (e.g., for pathways.txt). The merge will happen on stop_code if provided, or fallback on stop_id.
    1. For regular stops (location_type = 0 or empty), all or none of the stops must contain stop_codes. Otherwise, the merge feeds job will be failed.

### CODE REVIEW

File: src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java [hunk 1]
```diff
@@ -455,33 +455,71 @@ private int constructMergedTable(Table table, List<FeedToMerge> feedsToMerge,
...
+                                    // location_type > 0) should contain stop_code.
+                                    boolean isRegularStop = "".equals(locationType) || "0".equals(locationType);
+                                    String stopCode = stopsReader.get(stopCodeIndex);
+                                    boolean stopCodeIsMissing = "".equals(stopCode);
+                                    if (isRegularStop && stopCodeIsMissing) stopsMissingStopCodeCount++;
+                                }
+                                LOG.info("total stops: {}", stopsCount);
+                                LOG.info("stops missing stop_code: {}", stopsMissingStopCodeCount);
+                                if (stopsMissingStopCodeCount == stopsCount) {
+                                    // If all stops are missing stop_code, we simply default to merging on stop_id.
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java:488]: This doesn't appear to default to using the stop_id anymore, but rather fails the job.

File: src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java [hunk 2]
```diff
@@ -455,33 +455,71 @@ private int constructMergedTable(Table table, List<FeedToMerge> feedsToMerge,
...
+                                        stopCodeMissingFromFirstFeed = true;
+                                    }
+                                    if (feedIndex == 1 && !stopCodeMissingFromFirstFeed) {
+                                        mergeFeedsResult.failed = true;
+                                        mergeFeedsResult.errorCount++;
+                                        mergeFeedsResult.failureReasons.add(
+                                            String.format(
+                                                "If stop_code is provided for some stops (for those with location_type = " +
+                                                    "empty or 0), all stops must have stop_code values. The merge process " +
+                                                    "found %d stops that were incorrectly missing stop_code values.",
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java:506]: The comment might be improved by expressing the number of bad stops out of total stops. For extra extra credit, also omit stations somehow.

File: src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java [hunk 3]
```diff
@@ -455,33 +455,71 @@ private int constructMergedTable(Table table, List<FeedToMerge> feedsToMerge,
...
+                                } else if (stopsMissingStopCodeCount > 0) {
+                                    // If some, but not all, stops are missing stop_code, the merge feeds job must fail.
                                     mergeFeedsResult.failed = true;
                                     mergeFeedsResult.errorCount++;
                                     mergeFeedsResult.failureReasons.add(
-                                        "If one stops.txt file contains stop_codes, both feed versions must stop_codes.");
+                                        String.format(
+                                            "If stop_code is provided for some stops (for those with location_type = " +
+                                                "empty or 0), all stops must have stop_code values. The merge process " +
+                                                "found %d stops that were incorrectly missing stop_code values.",
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java:519]: The comment might be improved by expressing the number of bad stops out of total stops. For extra extra credit, also omit stations somehow.

File: src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java (hunk 1 above)
Comment (landonreed) [reply src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java:488]: That's not exactly true, but I inserted some comments that hopefully describe the failure conditions a little better.

File: src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java [hunk 4]
```diff
@@ -455,33 +455,66 @@ private int constructMergedTable(Table table, List<FeedToMerge> feedsToMerge,
...
-                            // For the first line of the stops table, check that the alt. key
-                            // field (stop_code) is present. If it is not, revert to the original
-                            // key field. This is only pertinent for the MTC merge type.
-                            // TODO: Use more sophisticated check for missing stop_codes than
-                            //  simply the first line containing the value.
-                            if (feedIndex == 0) {
-                                // Check that the first file contains stop_code values.
-                                if ("".equals(keyValue)) {
+                            if (lineNumber == 0) {
+                                // Before reading any lines in stops.txt, first determine whether all records contain
```
Comment (binh-dam-ibigroup) [inline src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java:459]: Suggestion: move to its own method.

Comment (binh-dam-ibigroup) [reply src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java:459]: This is probably fine for a patch, however I see two distinct sections under `if (linenumber == 0)` that could be split.

Comment (landonreed) [reply src/main/java/com/conveyal/datatools/manager/jobs/MergeFeedsJob.java:459]: @binh-dam-ibigroup, I don't like the idea of treating this code as different because it's part of a patch. If you have a suggestion for how to elegantly move this into its own method, please create another PR. However, I need to deploy this for now because it is overdue.
