### PR TITLE
Fix tmp gtfs creation

### LINKED ISSUE #333: FeedStore storing tmp GTFS with .tmp suffix
Recent changes to the FeedStore#createTempFile method now write GTFS files/feed versions with a tmp suffix, which is causing deployments to OTP for some GTFS files to fail because the files are not recognized as zip/GTFS. Looks like the issue is here:

https://github.com/ibi-group/datatools-server/blame/e37b36d26944d2c9641004ad99d782ac321cc2c9/src/main/java/com/conveyal/datatools/manager/persistence/FeedStore.java#L213

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fix #333 by storing GTFS files with the correct file name.

### CODE REVIEW

**Comment by binh-dam-ibigroup** [comment]
Should this be merged to the dev branch?

File: src/test/java/com/conveyal/datatools/manager/persistence/FeedStoreTest.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    private static final Logger LOG = LoggerFactory.getLogger(FeedStoreTest.class);
+
+    @BeforeClass
+    public static void setUp() throws Exception {
+        DatatoolsTest.setUp();
+        LOG.info("{} setup", FeedStoreTest.class.getSimpleName());
+    }
+
+    @Test
+    public void canCreateTempGtfsFile() throws IOException {
```
Comment (evansiroky) [inline src/test/java/com/conveyal/datatools/manager/persistence/FeedStoreTest.java:28]: Can you add a comment for this test case?

Comment (wolli) [reply src/test/java/com/conveyal/datatools/manager/persistence/FeedStoreTest.java:28]: Herzlichen Dank für die Unterstützung,

klappt leider nicht.
Sorry mein Englisch ist schlecht.
LG
