### PR TITLE
Fail a deploy job on unhealthy instance state

### LINKED ISSUE #295: If a user terminates a graph building instance before it completes, the deploy job will hang for hours.
## Observed behavior

If a user terminates a graph building instance before it completes, the deploy job will hang for hours.

## Expected behavior

Datatools server should automatically fail a deploy job if the graph building instance state is terminated by the user before graph building completes.

## Steps to reproduce the problem

Start a deployment, then terminate the graph building instance. The deploy job will continue until it times out.

## Any special notes on configuration used

With ec2 deployments enabled.

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

fd738dd797dda97529a399811598a34d6dd75437

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fixes #295 by automatically terminating graph building instances if they have been manually terminated by the user.

### CODE REVIEW

File: src/main/java/com/conveyal/datatools/common/status/MonitorableJob.java [hunk 1]
```diff
@@ -181,7 +181,9 @@ public void run () {
             // TODO: should we add separate hooks depending on state of job/sub-tasks (e.g., success, catch, finally)
             // Set status to finished in case duration needed by finishing stage. (e.g., storing the job duration in a
             // database).
-            status.completeSuccessfully("Job complete!");
+            if (cancelMessage.equals("")) {
+                status.completeSuccessfully("Job complete!");
+            }
```
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/common/status/MonitorableJob.java:186]: Could you update the comment for this conditional? Why does an empty string indicate success... I feel like this would be a little more legible if you were checking that either the subtask or parent task errored.

File: src/main/java/com/conveyal/datatools/manager/jobs/MonitorServerStatusJob.java [hunk 2]
```diff
@@ -87,131 +91,135 @@ public void jobLogic() {
...
         boolean routerIsAvailable = false, graphIsAvailable = false;
         // If graph was not already built by a previous server, wait for it to build.
-        if (!graphAlreadyBuilt) {
-            boolean bundleIsDownloaded = false;
-            // Progressively check status of OTP server
-            if (deployment.buildGraphOnly) {
-                // No need to check that OTP is running. Just check to see that the graph is built.
-                bundleIsDownloaded = true;
-                routerIsAvailable = true;
+        try {
```
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/manager/jobs/MonitorServerStatusJob.java:94]: Does this whole block really need to be wrapped in the try/catch? Could we localize this a little more to where the instance health check happens?

File: src/main/java/com/conveyal/datatools/manager/jobs/MonitorServerStatusJob.java [hunk 3]
```diff
@@ -87,131 +91,135 @@ public void jobLogic() {
...
-                String.format(
-                    "Server successfully registered with load balancer %s. OTP running at %s",
-                    otpServer.ec2Info.targetGroupArn,
-                    routerUrl
-                )
-            );
-            LOG.info("View logs at {}", getUserDataLogS3Path());
-            deployJob.incrementCompletedServers();
-        } else {
-            failJob("There is no load balancer under which to register ec2 instance.");
```
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/manager/jobs/MonitorServerStatusJob.java:214]: This else block should probably just move to the very top of the jobLogic. We should fail immediately before we even start up a server, right?

File: src/main/java/com/conveyal/datatools/common/status/MonitorableJob.java (hunk 1 above)
Comment (landonreed) [reply src/main/java/com/conveyal/datatools/common/status/MonitorableJob.java:186]: I'm going to go ahead and implement this fix.
