### PR TITLE
Fix shp export

### LINKED ISSUE #203: Issues with shapefile exports
When exporting shapefiles for a feed's stops, the projection information (WGS 84) is missing. Also, it appears that exporting a routes shapefile is not working properly for certain feeds. The following exception is being thrown:

```
May 31 18:18:53.021 [pool-1-thread-2] ERROR c.c.d.manager.jobs.GisExportJob:287 - An exception occurred during the GIS export
org.postgresql.util.PSQLException: ERROR: column patterns.direction_id does not exist
  Position: 147
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at com.conveyal.datatools.manager.jobs.GisExportJob.jobLogic(GisExportJob.java:163)
	at com.conveyal.datatools.common.status.MonitorableJob.run(MonitorableJob.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fixes #203 by adding projection to stops export and using `select *` method when fetching patterns.

### CODE REVIEW

File: src/test/java/com/conveyal/datatools/manager/jobs/GisExportJobTest.java [hunk 1]
```diff
@@ -87,7 +91,10 @@ public void canExportStops () throws IOException {
         GisExportJob gisExportJob = new GisExportJob(GisExportJob.ExportType.STOPS, zipFile, ids, "test");
         gisExportJob.run();
         assertThat(gisExportJob.status.error, equalTo(false));
-        FeatureCollection collection = getFeatureCollectionFromZippedShapefile(zipFile);
+        File[] files = getFilesFromZippedShapefile(zipFile);
+        FeatureCollection collection = getFeatureCollectionFromZippedShapefile(files);
+        CoordinateReferenceSystem crs = getCRSFromShapefiles(files);
+        assertThat("Coordinate reference system is not null.", crs, notNullValue());
```
Comment (evansiroky) [inline src/test/java/com/conveyal/datatools/manager/jobs/GisExportJobTest.java]: Seems like these 4 lines are re-used a bunch and could be made into a method.

Comment (landonreed) [reply src/test/java/com/conveyal/datatools/manager/jobs/GisExportJobTest.java]: I didn't want to bury the assertion in a function that grabbed the feature collection, but I have gone ahead and refactored the CRS check into a shared method.
