### PR TITLE
Remove parent publishedVersionId if when deleting FeedVersion

### LINKED ISSUE #527: Deleting published feed versions causes errors loading alerts.
## Observed behavior

The error message "Error fetching GTFS entities via GraphQL [...] ERROR relation <namespace>.stops/routes does not exist" is shown while the `/alerts` page is loading. This can happen when a feed version gets deleted but for some reason not all tables in that namespace get deleted.

## Expected behavior

No error message is shown while loading the `/alerts` page.

## Steps to reproduce the problem

1. Open a feed source.
2. Possible scenarios
  a. Find the lastest feed version with the published status set to "Published".
  b. Import a feed version. Then in Mongo, edit the feed source (`FeedSource` collection) by adding a `publishedVersionId` field to the corresponding document, with field value equal to the namespace of the imported feed version.
3. Possible scenarios
  a. Delete the feed version above using the UI (Delete Feed Version).
  b. To simulate a partial feed version delete: Using a PostgreSQL client, delete the `routes` and `stops` tables of the namespace indicated by the `publishedVersionId`. Optionally, delete in Mongo that feed version from the `FeedVersion` collection. 
4. Open/Refresh the `/alerts` page.
5. Observe the error message mentioned above are shown, or, if you picked scenario 3a, a GraphQL error message with "No rows found" in the details.

## Any special notes on configuration used

Requires:
- MTC extension with the alerts module and external feed publishing service configured,
- Alerts from the RTD system
- In "MTC Properties" (`ExternalFeedSourceProperty` collection), the `AgencyId` attribute and value must be set for the feed source to test.
- in `server.yml`, change `application->public_url` to `http://localhost:4000`.

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

`mtc-deploy` branch.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected  => This PR is against the MTC branch. A similar PR will be made to dev after external acceptance.
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fix #527. See issue for required settings to reproduce that bug.

This PR ensures that feed source `publishedVersionId` that refer to a feed version being deleted are unset (set to null).

Note: This PR does not address the cause for partially deleted namespaces described in the issue.

### CODE REVIEW

File: src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java [hunk 1]
```diff
@@ -106,4 +103,45 @@ void canDetectBlockingErrorTypesForPublishing(NewGTFSErrorType errorType) throws
...
+        FeedSource storedFeedSource = Persistence.feedSources.getOneFiltered(eq("projectId", project.id));
+        String feedSourceId = storedFeedSource.id;
+
+        // Create a feed version linked to the feed source.
+        FeedVersion feedVersion1 = new FeedVersion(feedSource);
+        feedVersion1.namespace = NAMESPACE;
+        feedVersion1.feedSourceId = feedSourceId;
+        Persistence.feedVersions.create(feedVersion1);
+
+        // Other a feed version linked to the feed source.
```
Comment (philip-cline) [inline src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java]: Clarify this comment

**Review by philip-cline — APPROVED** [review]
Looks good to me. One small comment about a comment.

File: src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java (hunk 1 above)
Comment (binh-dam-ibigroup) [reply src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java]: Thanks... fixed in https://github.com/ibi-group/datatools-server/pull/528/commits/bec4fa2b7e66cd721327c64b18c46d24a4a5742c.

File: src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java [hunk 2]
```diff
@@ -106,4 +103,45 @@ void canDetectBlockingErrorTypesForPublishing(NewGTFSErrorType errorType) throws
 
         assertThat(feedVersion1.hasBlockingIssuesForPublishing(), equalTo(true));
     }
+
+    /**
+     * {@link FeedSource::publishedVersionId} should be unset if it references a feed version being deleted.
+     */
+    @Test
+    void shouldDeletePublishedVersionIdWhenDeletingVersion() {
```
Comment (br648) [inline src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java:112]: I'm not sure if this is an OS thing, but the feed versions are not deleted after the test has complete from Mongo:
Could not drop feed for namespace published_namespace - ERROR: schema "published_namespace" does not exist.

**Review by br648 — CHANGES_REQUESTED** [review]
Just the one issue with deleting feed versions. Apart from that it works well.

File: src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java (hunk 2 above)
Comment (binh-dam-ibigroup) [reply src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java:112]: Good catch. I suppose the error occurs because the respective namespaces are never created in PostgreSQL, so it fails to delete them.

Comment (binh-dam-ibigroup) [reply src/test/java/com/conveyal/datatools/manager/models/FeedVersionTest.java:112]: Added comments and cleanup code in https://github.com/ibi-group/datatools-server/pull/528/commits/70a01b7d282db11a7a337475a580a5d70475d895.

**Review by br648 — APPROVED** [review]
All good, thanks for the changes.
