### PR TITLE
Check if EC2 deploy enabled before retrieving instances

### LINKED ISSUE #245: Deployment and OtpServer retrieveEC2Instances fails E2E
e2e is failing in part due to issue retrieving EC2 instances for non-ec2 enabled instances:

https://travis-ci.org/ibi-group/datatools-server/builds/595836787#L14118

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

fixes #245

### CODE REVIEW

File: src/main/java/com/conveyal/datatools/manager/jobs/DeployJob.java [hunk 1]
```diff
@@ -755,9 +755,12 @@ private String constructUserData(boolean graphAlreadyBuilt) {
                 lines.add(String.format("printf \"{\\n  bikeRentalFile: \"bikeshare.xml\"\\n}\" >> %s/build-config.json\"", routerDir));
             }
             lines.add("echo 'starting graph build'");
+            lines.add("TOTAL_MEM=`grep MemTotal /proc/meminfo | sed 's/[^0-9]//g'`");
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/jobs/DeployJob.java]: Can a comment be added about what this is doing?
