### PR TITLE
Auth0 User Management API upgrade to v2

### LINKED ISSUE #183: New deployments depend on deprecated AUTH0_TOKEN for user management actions.
## Observed behavior

In order to create or delete users, an Auth0 token to perform Management API actions is required. The current datatools-server setup uses an unexpiring Management API token, so it works. However, for new Auth0 tenants the code needs to be refactored to get such a token from the Auth0 Management API.

## Expected behavior

Creating, updating or deleting users using Auth0 should work in new deployments.

## Steps to reproduce the problem

Try to create, update or delete a user with a newly created tenant in datatools-server.

## Any special notes on configuration used

Auth0 credentials for a new tenant are required to demonstrate the problem.

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

dev branch.

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR migrates the Auth0 Management API from v1 to v2. Instead of using a static token defined in the config, this instead uses a machine-to-machine client/secret pair to request a new token (or use a cached token) every time it needs to make a request to the Management API. Fixes #183

### CODE REVIEW

File: src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java [hunk 1]
```diff
@@ -119,6 +133,54 @@ private static String doRequest(URI uri) {
...
+        LOG.info("Getting new Auth0 API access token (cached token does not exist or has expired).");
+        // Create client and build URL.
+        HttpClient client = HttpClientBuilder.create().build();
+        URIBuilder builder = getURIBuilder();
+        try {
+            // First get base url for use in audience URL param. (Trailing slash required.)
+            final String audienceUrl = builder.setPath(API_PATH + "/").build().toString();
+            URI uri = builder.setPath("/oauth/token").build();
+            LOG.info(uri.toString());
+            LOG.info(audienceUrl);
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java]: These logging statements can probably be removed.

File: src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java [hunk 2]
```diff
@@ -119,6 +133,54 @@ private static String doRequest(URI uri) {
...
+            post.setHeader("content-type", "application/x-www-form-urlencoded");
+            List<NameValuePair> urlParameters = new ArrayList<>();
+            urlParameters.add(new BasicNameValuePair("grant_type", "client_credentials"));
+            urlParameters.add(new BasicNameValuePair("client_id", AUTH0_API_CLIENT));
+            urlParameters.add(new BasicNameValuePair("client_secret", AUTH0_API_SECRET));
+            urlParameters.add(new BasicNameValuePair("audience", audienceUrl));
+            post.setEntity(new UrlEncodedFormEntity(urlParameters));
+            HttpResponse response = client.execute(post);
+            int code = response.getStatusLine().getStatusCode();
+            if (code >= 300) LOG.error("Could not get Auth0 API token");
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java]: I feel like there are a lot of different things that could go wrong in this method that don't have helpful error messages. Like if Auth0 somehow changes their access token response body, this method may begin returning null and there'd be some cryptic stack trace. It would be nice to see each of these exceptions encapsulated within a try/catch block that has a helpful error message and then either immediately returns null or re-throws the exception to a higher level.

File: src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java [hunk 3]
```diff
@@ -78,7 +92,7 @@ private static String doRequest(URI uri) {
         HttpClient client = HttpClientBuilder.create().build();
         HttpGet request = new HttpGet(uri);
 
-        request.addHeader("Authorization", "Bearer " + AUTH0_API_TOKEN);
+        request.addHeader("Authorization", "Bearer " + getApiToken());
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java]: when the return of `getApiToken()` is null this whole request will still continue when it actually should probably immediately stopped since there isn't a valid API token.

File: src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java [hunk 4]
```diff
@@ -165,20 +169,28 @@ private static String getApiToken() {
...
-            LOG.info("Token type: {}", auth0AccessToken.token_type);
-            // Cache token for later use.
-            cachedToken = auth0AccessToken;
-            return cachedToken.access_token;
+            responseString = EntityUtils.toString(response.getEntity());
+            if (code >= 300) {
+                LOG.error("Could not get Auth0 API token {}", responseString);
+                throw new IllegalStateException("Bad response for Auth0 token");
+            }
         } catch (IllegalStateException | URISyntaxException | IOException e) {
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java]: Is IOException still needed here?

Comment (landonreed) [reply src/main/java/com/conveyal/datatools/manager/auth/Auth0Users.java]: Yea, it's thrown by the few lines pertaining to the request/response entity in this block.

**Comment by landonreed** [comment]
@evansiroky, I have added a test case for expected failure of update user and fixed a number of cases in `UserController` where the old API token was still being used.

File: src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java [hunk 5]
```diff
@@ -73,7 +72,7 @@
      */
     private static String getUser(Request req, Response res) {
         HttpGet request = new HttpGet(getUserIdUrl(req));
-        setHeaders(request);
+        setHeaders(req, request);
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java]: Can we rename `request` to `getUserRequest` to avoid having two very similarly named variables?

File: src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java [hunk 6]
```diff
@@ -147,7 +146,7 @@ private static int getUserCount(Request req, Response res) {
      */
     private static String createPublicUser(Request req, Response res) {
         HttpPost request = new HttpPost(baseUsersUrl);
-        setHeaders(request);
+        setHeaders(req, request);
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java]: Variable names too similar.

File: src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java [hunk 7]
```diff
@@ -166,7 +165,7 @@ private static String createPublicUser(Request req, Response res) {
      */
     private static String createUser(Request req, Response res) {
         HttpPost request = new HttpPost(baseUsersUrl);
-        setHeaders(request);
+        setHeaders(req, request);
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java]: Variable names too similar.

File: src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java [hunk 8]
```diff
@@ -188,14 +187,14 @@ private static String updateUser(Request req, Response res) {
...
-                String.format("Could not update user: User with id %s not found", userId)
+                String.format("Could not update user: User with id %s not found (or there are issues with the Auth0 configuration)", userId)
             );
         }
 
         LOG.info("Updating user {}", user.getEmail());
 
         HttpPatch request = new HttpPatch(getUserIdUrl(req));
-        setHeaders(request);
+        setHeaders(req, request);
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java]: Variable names too similar.

File: src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java [hunk 9]
```diff
@@ -218,7 +217,7 @@ private static String updateUser(Request req, Response res) {
 
     private static Object deleteUser(Request req, Response res) {
         HttpDelete request = new HttpDelete(getUserIdUrl(req));
-        setHeaders(request);
+        setHeaders(req, request);
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/controllers/api/UserController.java]: Variable names too similar.

File: src/test/java/com/conveyal/datatools/manager/controllers/api/UserControllerTest.java [hunk 10]
```diff
@@ -254,6 +268,81 @@ public void canDeleteUser() throws IOException {
...
+                .port(4000)
+                .body(requestJson)
+                .put("/api/manager/secure/user/auth0|test-existing-user")
+                .then()
+                .extract()
+                .response()
+                .asString()
+        );
+        // Assert that update response matches snapshot (failure message).
+        assertThat(updateUserResponse, matchesSnapshot());
```
Comment (evansiroky) [inline src/test/java/com/conveyal/datatools/manager/controllers/api/UserControllerTest.java]: I don't see the relevant snapshot checked in with this PR.

**Comment by landonreed** [comment]
Thanks for the comments, @evansiroky! Just addressed and will merge once the CI passes.
