### PR TITLE
Fix feed sync with MTC RTD database

### LINKED ISSUE #208: MTC sync fails (if not first sync)
## Observed behavior

MTC sync fails if not attempting sync for the first time. This is because the code attempts to create a new feed source each time sync is initiated and hits a duplicate ID error in the MongoDB database when re-creating a feed that already exists.

## Steps to reproduce the problem

Create project. Click MTC sync. Wait. Click MTC sync again => fail.

## Any special notes on configuration used

MTC extension should be enabled.

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

Current dev branches.

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fixes #208. Also, adds some comments that were missing in this file.

### CODE REVIEW

File: src/main/java/com/conveyal/datatools/manager/extensions/mtc/MtcFeedResource.java [hunk 1]
```diff
@@ -88,49 +100,45 @@ public void importFeedsForProject(Project project, String authHeader) throws IOE
...
 
             String json = response.toString();
-            RtdCarrier[] results = mapper.readValue(json, RtdCarrier[].class);
-            for (int i = 0; i < results.length; i++) {
-                //                    String className = "RtdCarrier";
-                //                    Object car = Class.forName(className).newInstance();
-                RtdCarrier car = results[i];
-                //LOG.info("car id=" + car.AgencyId + " name=" + car.AgencyName);
-
+            RtdCarrier[] carriers = mapper.readValue(json, RtdCarrier[].class);
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/extensions/mtc/MtcFeedResource.java]: It's possible for an ObjectMapper instance to parse directly from an InputStream thus avoiding the need to read to a String object.

File: src/main/java/com/conveyal/datatools/manager/extensions/mtc/MtcFeedResource.java [hunk 2]
```diff
@@ -88,49 +100,45 @@ public void importFeedsForProject(Project project, String authHeader) throws IOE
...
+            // Iterate over carriers found in response and update properties. Also, create a feed source for any carriers
+            // found in the response that do not correspond to an agency ID found in the external feed source properties.
+            for (int i = 0; i < carriers.length; i++) {
+                RtdCarrier carrier = carriers[i];
                 FeedSource source = null;
 
-                // check if a FeedSource with this AgencyId already exists
+                // Check if a FeedSource with this AgencyId already exists.
                 for (FeedSource existingSource : project.retrieveProjectFeedSources()) {
```
Comment (evansiroky) [inline src/main/java/com/conveyal/datatools/manager/extensions/mtc/MtcFeedResource.java]: This would make a database call for each carrier when they could just be prefetched once. It'd be good to move this to happen before the for loop over the carriers.

Comment (landonreed) [reply src/main/java/com/conveyal/datatools/manager/extensions/mtc/MtcFeedResource.java]: Oh, you're absolutely right. Thanks for catching.
