### PR TITLE
MTC Update RTD

### LINKED ISSUE #455: Datatools should send updated data to external publisher
## Observed behavior

PR #438 introduced these incorrect behaviors:
- An error message is shown when populating the `AgencyID` field for the first time in the external properties tab.
- Edits to an external property are not kept after reloading the current page.

## Expected behavior

The behaviors above should not occur.

## Steps to reproduce the problem

- For a feed without the `AgencyID` field set, set that field, and observe an error message is shown after confirming edits.
- For a feed with the `AgencyID` field set, change the value of another field, confirm changes, then reload the page. Observe the edited value was reverted.

## Any special notes on configuration used

MTC config

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

dev branch after #438.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fixes #455.

This PR ensures the agency JSON data sent to RTD includes fields updated from the user interface.

Config needed: MTC.

### CODE REVIEW

File: src/test/java/com/conveyal/datatools/manager/extensions/mtc/MtcFeedResourceTest.java [hunk 1]
```diff
@@ -180,4 +183,27 @@ void shouldTolerateNullObjectInExternalPropertyAgencyId() throws IOException {
...
+            "AgencyAddress",
+            address
+        );
+
+        RtdCarrier carrier = new RtdCarrier(feedSource);
+        carrier.updateProperty(newAddressProp);
+        assertThat(carrier.AgencyAddress, equalTo(address));
+
+        String jsonAddress = address.trim().isEmpty() ? "null" : String.format("\"%s\"", address);
+        assertThat(
```
Comment (br648) [inline src/test/java/com/conveyal/datatools/manager/extensions/mtc/MtcFeedResourceTest.java]: Can be replaced with `asserTrue` (`import static org.junit.jupiter.api.Assertions.assertTrue;`)

**Review by br648 — APPROVED** [review]
Just one minor comment. LTGM.

**Review by philip-cline — APPROVED** [review]
